In [ ]:
#TODO
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
%cd gdrive/MyDrive/

/content/gdrive/MyDrive


In [ ]:
! git clone https://github.com/zhuhao-nju/mofanerf.git

In [ ]:
%cd mofanerf

/content/gdrive/MyDrive/mofanerf


In [ ]:
import sys
sys.path

['/content',
 '/env/python',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.9/dist-packages/IPython/extensions',
 '/root/.ipython']

In [ ]:
import sys
sys.path.append("/usr/local/lib/python3.9/site-packages")

In [ ]:
#can take forever
!pip install dlib==19.22.1 -vvv

Using pip 22.0.4 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-hc1v7ys2
Created temporary directory: /tmp/pip-req-tracker-41uwgpv5
Initialized build tracking at /tmp/pip-req-tracker-41uwgpv5
Created build tracker: /tmp/pip-req-tracker-41uwgpv5
Entered build tracker: /tmp/pip-req-tracker-41uwgpv5
Created temporary directory: /tmp/pip-install-k05hu653
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
2 location(s) to search for versions of dlib:
* https://pypi.org/simple/dlib/
* https://us-python.pkg.dev/colab-wheels/public/simple/dlib/
Fetching project page and analyzing links: https://pypi.org/simple/dlib/
Getting page https://pypi.org/simple/dlib/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/dlib/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connectio

In [ ]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 24.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 97.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.7/489.7 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 831.4/831.4 MB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.1/22.1 MB 72.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 680.7/680.7 KB 60.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.8/75.8 KB 11.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 709.8/709.8 KB 52.1 MB/s eta 0:00:

In [ ]:
%cd /content/gdrive/MyDrive/mofanerf

/content/gdrive/MyDrive/mofanerf


In [ ]:
!chmod +x download_pretrained_models.sh
#need to run this line first to give permission 

In [ ]:
%%bash 
./download_pretrained_models.sh

pretrained_models.tar.gz has already been downloaded.
pretrained_models.tar.gz: HTML document, ASCII text, with very long lines, with no line terminators
pretrained models have been extracted to ./logs/



gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now


In [ ]:
#Go modify the file instead as following to run on GPU with only 10GB memory 
#"Reminder: If your GPU has memory of only 10GB, we recommend that you modify parameters "netchunk","chunk" from 196608 to 16384, 
#"N_rand" from 1024 to 64 in ./configs/exp_mofanerf.txt."
#to run on google colab premium GPU run this line:
#!pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

In [ ]:
!python ./tools/wildData_preprocess.py --filePath ./data/fit/

/content/gdrive/MyDrive/mofanerf/tools/fit_data_pre/AlignmentCode/wild_fit_base.py:200: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  t = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
campos: [[array([0.99635376]) array([0.01768841]) array([-0.08346435])
  array([-1.27429686])]
 [array([-0.00069751]) array([0.97992861]) array([0.19934752])
  array([3.0435499])]
 [array([0.08531524]) array([-0.19856243]) array([0.9763679])
  array([14.90675416])]
 [0 0 0 1]]
/content/gdrive/MyDrive/mofanerf/./tools/wildData_preprocess.py:24: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for 

In [ ]:
!python run_fit.py --filePath ./data/fit/segRelRes/1.png

1
Found ckpts ['./logs/mofanerf_0to300/300000.tar']
Reloading from ./logs/mofanerf_0to300/300000.tar
Not ndc!
/content/gdrive/MyDrive/mofanerf/run_fit.py:186: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  crop_img_raw_uint8 = imageio.imread(src_path)
load poses:  ./data/fit/pose_1.npy
(4, 4) (68, 2)
!!!!! no crop !!!!
/content/gdrive/MyDrive/mofanerf/run_fit.py:191: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance:

In [ ]:
!python run_fit.py --filePath ./data/fit/segRelRes/1.png --renderType rendering  

1
Found ckpts ['./logs/mofanerf_0to300/300000.tar']
Reloading from ./logs/mofanerf_0to300/300000.tar
Not ndc!
/content/gdrive/MyDrive/mofanerf/run_fit.py:186: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  crop_img_raw_uint8 = imageio.imread(src_path)
load poses:  ./data/fit/pose_1.npy
(4, 4) (68, 2)
!!!!! no crop !!!!
/content/gdrive/MyDrive/mofanerf/run_fit.py:191: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance:

In [ ]:
!python run_refine.py --name facescape --nerf_folder ./data/fit/fitting/segRelRes_1/render/

------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./logs/refine
cluster_path: features_clustered_010.npy
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
gt_folder: gt_folder
how_many: 50
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
loadSize: 512
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
nThreads: 2
n_blocks_global: 9
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 4
n_local_enhancers: 1
name: facescape
nef: 16
nerf_folder: ./data/fit/fitting/segRelRes_1/render/
netG: global
ngf: 32
niter_fix_global: 0
no_flip: True
no_instance: True
norm: instance
ntest: inf
onnx: None
output_nc: 3
phase: test
resize_or_crop: resize
result_folder: result_folder
results_dir: ./results/
serial_batches: False
tf_log: False
use_dropout: False
use_encoded_image: False
verbose: False
whic